<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.taxdataexchange.sdks</groupId>

    <artifactId>TaxW2GDocumentGenerator</artifactId>

    <version>2026.0.0-SNAPSHOT</version>

    <properties>

        <java.version>17</java.version>

        <maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.taxdataexchange.core</groupId>
            <artifactId>taxdoc.generator.core.2026-660</artifactId>
            <version>2026.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>

        <extensions>
            <extension>
                <groupId>com.google.cloud.artifactregistry</groupId>
                <artifactId>artifactregistry-maven-wagon</artifactId>
                <version>2.2.0</version>
            </extension>
        </extensions>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <verbose>false</verbose>
                </configuration>
            </plugin>

        </plugins>

    </build>

    <repositories>
        <repository>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>artifact-registry</id>
            <url>artifactregistry://us-central1-maven.pkg.dev/taxdochub-endpoints/tax-doc-generator-core-repo</url>
        </repository>
    </repositories>

</project>
